// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[slug].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/blog.tsx";
import * as $5 from "./routes/blog/analisis.tsx";
import * as $6 from "./routes/blog/anime.tsx";
import * as $7 from "./routes/blog/cine.tsx";
import * as $8 from "./routes/blog/gaming.tsx";
import * as $9 from "./routes/blog/manga.tsx";
import * as $10 from "./routes/blog/opinion.tsx";
import * as $11 from "./routes/blog/politica.tsx";
import * as $12 from "./routes/blog/reflexiones.tsx";
import * as $13 from "./routes/blog/religion.tsx";
import * as $14 from "./routes/blog/tecnologia.tsx";
import * as $15 from "./routes/feed.ts";
import * as $16 from "./routes/galeria.tsx";
import * as $17 from "./routes/index.tsx";
import * as $$0 from "./islands/ColorMode.tsx";
import * as $$1 from "./islands/Tabs.tsx";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/about.tsx": $3,
    "./routes/blog.tsx": $4,
    "./routes/blog/analisis.tsx": $5,
    "./routes/blog/anime.tsx": $6,
    "./routes/blog/cine.tsx": $7,
    "./routes/blog/gaming.tsx": $8,
    "./routes/blog/manga.tsx": $9,
    "./routes/blog/opinion.tsx": $10,
    "./routes/blog/politica.tsx": $11,
    "./routes/blog/reflexiones.tsx": $12,
    "./routes/blog/religion.tsx": $13,
    "./routes/blog/tecnologia.tsx": $14,
    "./routes/feed.ts": $15,
    "./routes/galeria.tsx": $16,
    "./routes/index.tsx": $17,
  },
  islands: {
    "./islands/ColorMode.tsx": $$0,
    "./islands/Tabs.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
